### ISSUE TITLE
Rendering an error

### ISSUE THREAD

**Issue by Base29** [InTeach/react-native-scroll-indicator#4]
Hello Guys ... I have installed and linked the package as mentioned in the instruction but I am having this error ... 

![image](https://user-images.githubusercontent.com/5220908/44936734-569f2900-ad8f-11e8-990a-feb720b0ea76.png)

**Comment by Base29** [comment]
any one ?

**Comment by Crash--** [comment]
This package is based on react-native-linear-gradient. The error you are seeing, it's because RNLG is not correctly installed. You can take a look at their documentation and try to install it manually https://github.com/react-native-community/react-native-linear-gradient

**Comment by imspikey** [comment]
Thanks you manual install worked for me 👍
